## Линейная независиомсть векторов

In [33]:
# Пусть даны вектора

e1 = [1., 0., 0.]
e2 = [0., 5., 0.]

# Вектора e1 и e2 называются независимымми если не тривиальная кобинация векторов [не с нулевыми коэфицентами]
# не равноа нулевому вектору
# то есть:

import numpy as np

e1 = np.array(e1)
e2 = np.array(e2)

print e1, e2


[1. 0. 0.] [0. 5. 0.]


In [18]:
-3*e1 + 2*e2 # линейно независимы


array([-3., 10.,  0.])

In [31]:
a = np.array([-3., 10., 0.])

3*e1 - 2*e2 + 1*a # Существует такая комбинация векторов, которая равна нулевому вектору, значит эти вектора зависимы

array([0., 0., 0.])

## Ранг матрицы

In [28]:
M = np.array([e1, e2, a])

M

array([[ 1.,  0.,  0.],
       [ 0.,  5.,  0.],
       [-3., 10.,  0.]])

In [29]:
# Ранг матрицы это максимальное количество линейно независимых строк или столбцов матрицы

In [30]:
np.linalg.matrix_rank(M)

2

## Задачи

In [57]:
# (1,0),(0,1),(−1,1)

a1 = np.array([1., 0.])
a2 = np.array([0., 1.])
a3 = np.array([-1., 1.])

M = np.array([a1, a2, a3])
print M

print np.linalg.matrix_rank(M), '\n----'

print 1*a1 -  1*a2 + 1*a3, '\nвектора ленийено зависимы'


# (1,0),(0,1)

a1 = np.array([1., 0.])
a2 = np.array([0., 1.])

print np.linalg.matrix_rank(np.array([a1, a2])) # линейно незавимсмы


# (1,0),(1,1) линейно незавимсмы

[[ 1.  0.]
 [ 0.  1.]
 [-1.  1.]]
2 
----
[0. 0.] 
вектора ленийено зависимы
2


## 2 манхэттенская норма вектора

$$
 \left\Vert x \right\Vert_{1} = \sum_{i=1}^n \left| x_{i} \right|.
$$

In [67]:
a = np.array([-1., 2., -1.])

np.linalg.norm(a, ord=1) # манхэттенская норма вектора

4.0

In [69]:
print 1. + 2. + 1.

4.0


## 3 скалярное произведение векторов a=(1,2,3) и b=(−3,1,1)?

Скалярное произведение в пространстве $\mathbb{R}^{n}$ для двух векторов $x = (x_{1}, \dots, x_{n})$ и $y = (y_{1}, \dots, y_{n})$ определяется как:

$$
\langle x, y \rangle = \sum_{i=1}^n x_{i} y_{i}.
$$

In [70]:
(-3*1) + (2 * 1) + (3 * 1)

2

In [73]:
a1, a2 = np.array([1., 2., 3.]), np.array([-3., 1., 1.])

a1.dot(a2)

2.0